package payment.sdk.android.demo.model

enum class AppCurrency(val code: String, val countryName: String) {
    AUD("AUD", "Australian Dollar"),
    BRL("BRL", "Brazilian Real"),
    CAD("CAD", "Canadian Dollar"),
    CHF("CHF", "Swiss Franc"),
    CNY("CNY", "Chinese Yuan"),
    EUR("EUR", "Euro"),
    GBP("GBP", "British Pound Sterling"),
    HKD("HKD", "Hong Kong Dollar"),
    INR("INR", "Indian Rupee"),
    JPY("JPY", "Japanese Yen"),
    KRW("KRW", "South Korean Won"),
    MXN("MXN", "Mexican Peso"),
    NOK("NOK", "Norwegian Krone"),
    NZD("NZD", "New Zealand Dollar"),
    SEK("SEK", "Swedish Krona"),
    SGD("SGD", "Singapore Dollar"),
    TRY("TRY", "Turkish Lira"),
    USD("USD", "United States Dollar"),
    ZAR("ZAR", "South African Rand"),
    AED("AED", "United Arab Emirates Dirham"),
    BHD("BHD", "Bahraini Dinar"),
    DZD("DZD", "Algerian Dinar"),
    ILS("ILS", "Israeli New Shekel"),
    JOD("JOD", "Jordanian Dinar"),
    KWD("KWD", "Kuwaiti Dinar"),
    LYD("LYD", "Libyan Dinar"),
    OMR("OMR", "Omani Rial"),
    QAR("QAR", "Qatari Riyal"),
    SAR("SAR", "Saudi Riyal"),
    TND("TND", "Tunisian Dinar"),
    ZWG("ZWG", "Zimbabwean Dollar")
}